language: node_js
node_js:
  - "8"

script:
  - npm run build
  - npm run test
  - grep -v ^/index.html .gitignore >.gitignore.tmp
  - mv .gitignore.tmp .gitignore

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
