language: node_js
node_js:
  - "8"

script:
  - git pull --tags
  - npm run build
  - npm run test
  - grep -v ^/index.html .gitignore >.gitignore.tmp
  - mv .gitignore.tmp .gitignore
  - git pull --ff-only

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
