#!/usr/bin/env bash

cd "$(dirname "$0")/.."

#cat >editions/material/tiddlers/content/material_
#ssss log --stat --pretty=oneline material/v0.1.9.. -- src/themes/material >

buildinfo_tid_body() {
  local dir="$1"
  local vprefix="$2"
  local ver="$3"
  local changes=$(git diff --pretty=oneline "$vprefix$ver..HEAD" -- "$dir" 2>&1)

  if [[ -n $changes ]]; then
    echo "Changes between version $ver and HEAD:"
    echo ''
    echo '```'
    echo "$changes" |
      grep -E -v '^[+-](created|modified):' |
      grep -E -v '^(diff|index) '
    echo '```'
  else
    echo "No changes between version $ver and HEAD."
  fi
}

buildinfo_tid() {
  local dir="$1"
  local vprefix="$2"
  local ver="$3"
  local now="$(TZ=UTC date +'%Y%m%d%H%M%S')"

  cat >"$out" <<EOS
title: $vprefix$ver-current
caption: >$ver
tags: $:/tags/ReleaseNotes
created: $now
modified: $now
released: $now

$(buildinfo_tid_body "$dir" "$vprefix" "$ver")
EOS
}

make_buildinfo() {
  local dir="$1"
  local vprefix="$2"
  local name=$(dirname $vprefix)
  local out="editions/material/tiddlers/content/${name}_current.tid"
  local ver=$(jq -r .version "$dir"/plugin.info)

  buildinfo_tid "$dir" "$vprefix" "$ver" >"$out"
}

make_buildinfo "src/themes/material" "material/v"

for plugin in caption mdc mdc-web mdc-web-cdn muuri; do
  make_buildinfo "src/plugins/$plugin" "$plugin/v"
done
