#!/usr/bin/env bash
set -o errexit

cd "$(dirname "$0")/.."

#cat >editions/material/tiddlers/content/material_
#ssss log --stat --pretty=oneline material/v0.1.9.. -- src/themes/material >

make_buildinfo() {
  local dir="$1"
  local vprefix="$2"
  local name=$(dirname $vprefix)
  local out="editions/material/tiddlers/content/${name}_current.tid"
  local ver=$(jq -r .version "$dir"/plugin.info)
  local now="$(date +'%Y%m%d%H%M%S')"

  cat >"$out" <<EOS
title: $vprefix$ver-current
caption: $ver-current
tags: $:/tags/ReleaseNotes
created: $now
modified: $now

Changed files between version $ver and HEAD:

\`\`\`
EOS

  git diff --pretty=oneline "$vprefix$ver..HEAD" -- "$dir" >"$out.tmp" 2>&1
  if [[ ! -s $out.tmp ]]; then
    echo 'No changes.' >"$out.tmp"
  fi

  cat "$out.tmp" >>"$out"
  rm "$out.tmp"

  cat >>"$out" <<EOS
\`\`\`
EOS
}

make_buildinfo "src/themes/material" "material/v"

for plugin in mdc mdc-web mdc-web-cdn muuri; do
  make_buildinfo "src/plugins/$plugin" "$plugin/v"
done
